apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-staging.af8c2bf4681684c84a9a7d97a3e8d243-512583250.sa-east-1.elb.amazonaws.com
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
      weight: 100
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
