apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.sockshop-dev.af8c2bf4681684c84a9a7d97a3e8d243-512583250.sa-east-1.elb.amazonaws.com
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop-dev.svc.cluster.local
